### ISSUE TITLE
🏎 Minor feature request: Enable scale view configuration for number questions in FHIR Survey Builder

### ISSUE THREAD

**Issue by iadereggalternova** [StanfordBDHG/phoenix#34]
### Problem

I've noticed that the ResearchKitOnFHIR package currently supports a scale view for various question types, which is fantastic. However, it appears that the functionality to configure this view for number type questions is not yet available in the FHIR survey builder. I believe this functionality could be highly beneficial for those of us using the FHIR survey builder to create more interactive and detailed surveys.

### Solution

Would it be possible to integrate scale view configuration options into the JSON schema for number type questions within the FHIR survey builder? I think this addition would make the survey builder even more versatile and useful for a broader range of use cases. I am confident that this enhancement would be well-received by the community.

I deeply appreciate the time and effort the team puts into developing this project. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
Thank you for the suggestion @iadereggalternova, we are adding this feature in #37.

**Comment by vishnuravi** [comment]
This feature has been completed and deployed. Closing this issue.
